### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by silaslaycock** [richardseifert/Hydra_pipeline#1]
Hi Richard,
Very happy to see your new Hydra pipeline, since the existing one does not work under pyraf....
Would you be able to help with some questions as I try to get it running?

Thanks,
Silas

I have simply copied your project folder to my Mac (anaconda3 running on high Sierra), and followed your "how to run" document. 

Falls over with:

$ python hydra_pipeline.py recipe-log indata/Hydra2016data
Traceback (most recent call last):
  File "hydra_pipeline.py", line 2, in <module>
    import libs.process as process
  File "/Users/silas_laycock/Hydra/Hydra_pipeline-master/libs/process.py", line 29
    self.dname=dname
                   ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by silaslaycock** [comment]
Is this a python version issue?

**Comment by richardseifert** [comment]
Hi Silas,

Yes, I can definitely help with any questions you have! The best email to reach me at is richardseifert@email.virginia.edu.

You're correct about the version issue. Unfortunately, at the moment the pipeline only works with Python 2.7. One thing you can try, if you're using an Anaconda python distribution, is to create a python 2.7 [conda environment](https://conda.io/docs/user-guide/tasks/manage-environments.html#).

Here's how you can make a conda 2.7 environment that should have all the requirements for the pipeline:
`conda create -n myenv python=2.7 numpy=1.11.3 astropy=1.2.1 scipy=0.18.1 bokeh matplotlib`

Let me know if you have any more questions!

Best,
Richard
